name = "Barovia"
hours_in_day = 24
minutes_in_hour = 60
leap_year_rule = "year % 4 == 0"
axial_tilt = 28.883333  # Keeping this from Forgotten Realms
solar_days_in_year = 364  # 13 months x 28 days

default_day = 1
default_month = "Yinyavr"
default_year = 751

[months.yinyavr]
name = "Yinyavr"
alt_name = "The Cold Moon"
days = 28

[months.fenravr]
name = "Fenravr"
alt_name = "The Wolf Moon"
days = 28

[months.martavr]
name = "Martavr"
alt_name = "The Raven Moon"
days = 28

[months.prylla]
name = "Prylla"
alt_name = "The Rain Moon"
days = 28

[months.mada]
name = "Mada"
alt_name = "The Maid Moon"
days = 28

[months.eyun]
name = "Eyun"
alt_name = "The Dragon Moon"
days = 28

[months.eyul]
name = "Eyul"
alt_name = "The War Moon"
days = 28

[months.ugavr]
name = "Ugavr"
alt_name = "The Wine Moon"
days = 28

[months.sintavr]
name = "Sintavr"
alt_name = "The Harvest Moon"
days = 28

[months.ottyavr]
name = "Ottyavr"
alt_name = "The Hunter's Moon"
days = 28

[months.neyavr]
name = "Neyavr"
alt_name = "The Ghost Moon"
days = 28

[months.dekavr]
name = "Dekavr"
alt_name = "The Cold Moon"
days = 28

[months.undekavr]
name = "Undekavr"
alt_name = "The Devil's Moon"
days = 28

[seasons.spring_equinox]
name = "Spring Equinox"
month = "Martavr"
day = 22

[seasons.summer_solstice]
name = "Summer Solstice"
month = "Eyul"
day = 1

[seasons.autumn_equinox]
name = "Autumn Equinox"
month = "Ottyavr"
day = 8

[seasons.winter_solstice]
name = "Winter Solstice"
month = "Undekavr"
day = 15

[moons.luna]
name = "Luna"
period = 28
full_on = "1 Yinyavr 751"
