name = ""
size = ""
mtype = ""
species = ""
alignment = ""
ac = 10
armor = ""
max_hp = "1d8"
avg_hp = 5
speed = 30
str = 10
dex = 10
con = 10
int = 10
wis = 10
cha = 10
vulnerable = ""
resist = ""
immune = ""
languages = ""
cr = 1
xp = 1
pb = 0
image_url = ""
notes = """
"""

[skills]
skill = 1

[senses]
perception = 10

[traits.feature]
name = ""
description = """
"""

[traits.spellcasting]
name = "Spellcasting"
description = """
"""
cantrips = []
spells = [
    [],
    []
]
slots = [0, 0]
slots_used = [0, 0]

[actions.action]
name = ""
description = """
"""

[legendary_actions.action]
name = ""
description = """
"""

[reactions.reaction]
name = ""
description = """
"""
