[Character]
name = "name"
species = "species"
cclass = "class"
level = 1
pronouns = "they/them"
max_hp = 10
cur_hp = 10
ac = 10
initiative_mod = 0
image_url = ""

[Character.senses]
darkvision = 0
perception = 10
